language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.7"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  # create snakemake env
  - conda create -q -n snakemake snakemake python=$TRAVIS_PYTHON_VERSION
  # add additional stuff to setup below

script:
  - source activate snakemake
  # run the workflow
  # put a test case into the subfolder test (e.g., use https://github.com/snakemake-workflows/ngs-test-data as a submodule)
  - >
    snakemake all
              --snakefile Snakefile
              --configfile config.yaml
              --directory test
              --config sample_id=ecoli_01
                       raw_read_path=data
                       reference_id=GCF_000005845.2
                       reference_table=reference_table.yaml
              --use-conda
              --conda-prefix conda_envs
              --cores 4
              -np
