# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.

# fix snakemake wrapper version: https://github.com/snakemake/snakemake-wrappers
wrapper_version: '0.39.0'

illumina_adapters: '$CONDA_PREFIX/share/trimmomatic/adapters/TruSeq3-PE-2.fa'

params:
    trimmomatic:
        trimmer: ['ILLUMINACLIP:illumina_adapters:2:30:10',
                  'SLIDINGWINDOW:4:20',
                  'MINLEN:25']
        extra: ''
    hisat2:
        align:
            extra: '-q --no-spliced-alignment --rna-strandness RF --dta --new-summary'
    featureCounts:
        CDS: '-F GTF -O -M --fraction -p -s 2 -t CDS -g ID'
        gene: '-F GTF -O -M --fraction -p -s 2 -t gene -g ID'
